bootstrap:
	lessc  --clean-css="--s1 --advanced --compatibility=ie8" less/style.less > css/style.css 
	lessc  --clean-css="--s1 --advanced --compatibility=ie8" less/fontawesome.less > css/fontawesome.css